[package]
name = "build-sitelinks"
version = "0.1.0"
edition = "2021"

[dependencies]
bzip2 = "0.4.3"
clap = { version = "4.0.29", features = ["derive"] }
lmdb-rkv = "0.14.0"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
unicode-casefold = "0.2.0"
zstd = "0.12.1"

